global:
  hosts:
    domain: ${domain}
    externalIP: ${external_ip}
  ingress:
    configureCertmanager: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls:
      enabled: true
      secretName: gitlab-tls

certmanager:
  install: true
  email: ${tls_email}

nginx-ingress:
  enabled: true
